/* 
 * uos-mf-api-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ApiAck
    /// </summary>
    [DataContract]
    public partial class ApiAck :  IEquatable<ApiAck>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiAck" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiAck() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiAck" /> class.
        /// </summary>
        /// <param name="Ack">Ack (required).</param>
        public ApiAck(string Ack = default(string))
        {
            // to ensure "Ack" is required (not null)
            if (Ack == null)
            {
                throw new InvalidDataException("Ack is a required property for ApiAck and cannot be null");
            }
            else
            {
                this.Ack = Ack;
            }
        }
        
        /// <summary>
        /// Gets or Sets Ack
        /// </summary>
        [DataMember(Name="ack", EmitDefaultValue=false)]
        public string Ack { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiAck {\n");
            sb.Append("  Ack: ").Append(Ack).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ApiAck);
        }

        /// <summary>
        /// Returns true if ApiAck instances are equal
        /// </summary>
        /// <param name="other">Instance of ApiAck to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiAck other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Ack == other.Ack ||
                    this.Ack != null &&
                    this.Ack.Equals(other.Ack)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Ack != null)
                    hash = hash * 59 + this.Ack.GetHashCode();
                return hash;
            }
        }
    }

}
