/* 
 * uos-mf-api-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Play
    /// </summary>
    [DataContract]
    public partial class Play :  IEquatable<Play>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Play" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Play() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Play" /> class.
        /// </summary>
        /// <param name="RoomId">RoomId (required).</param>
        /// <param name="_Play">_Play (required).</param>
        public Play(string RoomId = default(string), PlayScenesAndThemes _Play = default(PlayScenesAndThemes))
        {
            // to ensure "RoomId" is required (not null)
            if (RoomId == null)
            {
                throw new InvalidDataException("RoomId is a required property for Play and cannot be null");
            }
            else
            {
                this.RoomId = RoomId;
            }
            // to ensure "_Play" is required (not null)
            if (_Play == null)
            {
                throw new InvalidDataException("_Play is a required property for Play and cannot be null");
            }
            else
            {
                this._Play = _Play;
            }
        }
        
        /// <summary>
        /// Gets or Sets RoomId
        /// </summary>
        [DataMember(Name="roomId", EmitDefaultValue=false)]
        public string RoomId { get; set; }

        /// <summary>
        /// Gets or Sets _Play
        /// </summary>
        [DataMember(Name="play", EmitDefaultValue=false)]
        public PlayScenesAndThemes _Play { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Play {\n");
            sb.Append("  RoomId: ").Append(RoomId).Append("\n");
            sb.Append("  _Play: ").Append(_Play).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Play);
        }

        /// <summary>
        /// Returns true if Play instances are equal
        /// </summary>
        /// <param name="other">Instance of Play to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Play other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.RoomId == other.RoomId ||
                    this.RoomId != null &&
                    this.RoomId.Equals(other.RoomId)
                ) && 
                (
                    this._Play == other._Play ||
                    this._Play != null &&
                    this._Play.Equals(other._Play)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.RoomId != null)
                    hash = hash * 59 + this.RoomId.GetHashCode();
                if (this._Play != null)
                    hash = hash * 59 + this._Play.GetHashCode();
                return hash;
            }
        }
    }

}
