/* 
 * uos-mf-api-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PlayScenesAndThemes
    /// </summary>
    [DataContract]
    public partial class PlayScenesAndThemes :  IEquatable<PlayScenesAndThemes>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayScenesAndThemes" /> class.
        /// </summary>
        /// <param name="Scenes">Scenes.</param>
        /// <param name="Themes">Themes.</param>
        public PlayScenesAndThemes(List<Scene> Scenes = default(List<Scene>), List<Theme> Themes = default(List<Theme>))
        {
            this.Scenes = Scenes;
            this.Themes = Themes;
        }
        
        /// <summary>
        /// Gets or Sets Scenes
        /// </summary>
        [DataMember(Name="scenes", EmitDefaultValue=false)]
        public List<Scene> Scenes { get; set; }

        /// <summary>
        /// Gets or Sets Themes
        /// </summary>
        [DataMember(Name="themes", EmitDefaultValue=false)]
        public List<Theme> Themes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlayScenesAndThemes {\n");
            sb.Append("  Scenes: ").Append(Scenes).Append("\n");
            sb.Append("  Themes: ").Append(Themes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PlayScenesAndThemes);
        }

        /// <summary>
        /// Returns true if PlayScenesAndThemes instances are equal
        /// </summary>
        /// <param name="other">Instance of PlayScenesAndThemes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlayScenesAndThemes other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Scenes == other.Scenes ||
                    this.Scenes != null &&
                    this.Scenes.SequenceEqual(other.Scenes)
                ) && 
                (
                    this.Themes == other.Themes ||
                    this.Themes != null &&
                    this.Themes.SequenceEqual(other.Themes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Scenes != null)
                    hash = hash * 59 + this.Scenes.GetHashCode();
                if (this.Themes != null)
                    hash = hash * 59 + this.Themes.GetHashCode();
                return hash;
            }
        }
    }

}
