/* 
 * uos-mf-api-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SceneId
    /// </summary>
    [DataContract]
    public partial class SceneId :  IEquatable<SceneId>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SceneId" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SceneId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SceneId" /> class.
        /// </summary>
        /// <param name="_SceneId">_SceneId (required).</param>
        public SceneId(string _SceneId = default(string))
        {
            // to ensure "_SceneId" is required (not null)
            if (_SceneId == null)
            {
                throw new InvalidDataException("_SceneId is a required property for SceneId and cannot be null");
            }
            else
            {
                this._SceneId = _SceneId;
            }
        }
        
        /// <summary>
        /// Gets or Sets _SceneId
        /// </summary>
        [DataMember(Name="sceneId", EmitDefaultValue=false)]
        public string _SceneId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SceneId {\n");
            sb.Append("  _SceneId: ").Append(_SceneId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SceneId);
        }

        /// <summary>
        /// Returns true if SceneId instances are equal
        /// </summary>
        /// <param name="other">Instance of SceneId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SceneId other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._SceneId == other._SceneId ||
                    this._SceneId != null &&
                    this._SceneId.Equals(other._SceneId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._SceneId != null)
                    hash = hash * 59 + this._SceneId.GetHashCode();
                return hash;
            }
        }
    }

}
